### ISSUE TITLE
Client stuck on PortUnreachableException

### ISSUE THREAD

**Issue by francisdb** [tim-group/java-statsd-client#45]
`v3.1.0`

We create a single client for the lifetime of our services but after a while they get stuck on this PortUnreachableException. Probably our server is unreachable for a few seconds and the client never recovers. A restart of the service fixes the issue.

```
java.net.PortUnreachableException: null
    at sun.nio.ch.DatagramDispatcher.write0(DatagramDispatcher.java)
    at sun.nio.ch.DatagramDispatcher.write(DatagramDispatcher.java:51)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:65)
    at sun.nio.ch.DatagramChannelImpl.write(DatagramChannelImpl.java:605)
    at com.timgroup.statsd.NonBlockingUdpSender.blockingSend(NonBlockingUdpSender.java:72)
    at com.timgroup.statsd.NonBlockingUdpSender.access$000(NonBlockingUdpSender.java:13)
    at com.timgroup.statsd.NonBlockingUdpSender$2.run(NonBlockingUdpSender.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shankarshastri** [comment]
yes I am also facing the same issue.
Is there going to be a fix or a workaround?

**Comment by francisdb** [comment]
we switched to https://github.com/DataDog/java-dogstatsd-client

**Comment by shankarshastri** [comment]
How did you guys fix it in the other library?

**Comment by francisdb** [comment]
The problem is fixed there

**Comment by shankarshastri** [comment]
Will It Retry Or Raise A Exception?

**Comment by shankarshastri** [comment]
If statsd server is up and is stopped at midpoint. I am not getting any exception even after using java-dogstatsd-client.

**Comment by francisdb** [comment]
I suggest you create a new issue on that project
